// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAObvdKZUmdYtxBMi8gHWmnEgkgJjNywDQ',
    appId: '1:220655003141:web:53df93b4fe1bdf15f09e6c',
    messagingSenderId: '220655003141',
    projectId: 'np-career',
    authDomain: 'np-career.firebaseapp.com',
    storageBucket: 'np-career.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL38Xh_y4pKahkvmkQpjXJswtPKmawr2A',
    appId: '1:220655003141:android:6d5e977684af595af09e6c',
    messagingSenderId: '220655003141',
    projectId: 'np-career',
    storageBucket: 'np-career.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa6ww2HT6bPlOtrOLom5bQ_q6Mp0LLLvY',
    appId: '1:220655003141:ios:5f0fa9a44df92e63f09e6c',
    messagingSenderId: '220655003141',
    projectId: 'np-career',
    storageBucket: 'np-career.firebasestorage.app',
    iosBundleId: 'com.example.npCareer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa6ww2HT6bPlOtrOLom5bQ_q6Mp0LLLvY',
    appId: '1:220655003141:ios:5f0fa9a44df92e63f09e6c',
    messagingSenderId: '220655003141',
    projectId: 'np-career',
    storageBucket: 'np-career.firebasestorage.app',
    iosBundleId: 'com.example.npCareer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAObvdKZUmdYtxBMi8gHWmnEgkgJjNywDQ',
    appId: '1:220655003141:web:f1480bdb610a61ccf09e6c',
    messagingSenderId: '220655003141',
    projectId: 'np-career',
    authDomain: 'np-career.firebaseapp.com',
    storageBucket: 'np-career.firebasestorage.app',
  );

}