enum EnumCity {
  anGiang("An Giang"),
  baRiaVungTau("Bà Rịa Vũng Tàu"),
  bacLieu("Bạc Liêu"),
  bacGiang("Bắc Giang"),
  bacKan("Bắc Kạn"),
  bacNinh("Bắc Ninh"),
  benTre("Bến Tre"),
  binhDuong("Bình Dương"),
  binhDinh("Bình Định"),
  binhPhuoc("Bình Phước"),
  binhThuan("Bình Thuận"),
  caMau("Cà Mau"),
  caoBang("Cao Bằng"),
  canTho("Cần Thơ"),
  daNang("Đà Nẵng"),
  dakLak("Đắk Lắk"),
  dakNong("Đắk Nông"),
  dienBien("Điện Biên"),
  dongNai("Đồng Nai"),
  dongThap("Đồng Tháp"),
  giaLai("Gia Lai"),
  haGiang("Hà Giang"),
  haNam("Hà Nam"),
  haNoi("Hà Nội"),
  haTinh("Hà Tĩnh"),
  haiDuong("Hải Dương"),
  haiPhong("Hải Phòng"),
  hauGiang("Hậu Giang"),
  hoaBinh("Hòa Bình"),
  hungYen("Hưng Yên"),
  khanhHoa("Khánh Hòa"),
  kienGiang("Kiên Giang"),
  konTum("Kon Tum"),
  laiChau("Lai Châu"),
  langSon("Lạng Sơn"),
  laoCai("Lào Cai"),
  lamDong("Lâm Đồng"),
  longAn("Long An"),
  namDinh("Nam Định"),
  ngheAn("Nghệ An"),
  ninhBinh("Ninh Bình"),
  ninhThuan("Ninh Thuận"),
  phuTho("Phú Thọ"),
  phuYen("Phú Yên"),
  quangBinh("Quảng Bình"),
  quangNam("Quảng Nam"),
  quangNgai("Quảng Ngãi"),
  quangNinh("Quảng Ninh"),
  quangTri("Quảng Trị"),
  socTrang("Sóc Trăng"),
  sonLa("Sơn La"),
  tayNinh("Tây Ninh"),
  thaiBinh("Thái Bình"),
  thaiNguyen("Thái Nguyên"),
  thanhHoa("Thanh Hóa"),
  thanhPhoHue("Thành phố Huế"),
  tienGiang("Tiền Giang"),
  tpHoChiMinh("TP Hồ Chí Minh"),
  traVinh("Trà Vinh"),
  tuyenQuang("Tuyên Quang"),
  vinhLong("Vĩnh Long"),
  vinhPhuc("Vĩnh Phúc"),
  yenBai("Yên Bái");

  final String label;

  const EnumCity(this.label);
}
