enum EnumTypeJobCategory {
  babysitter("Babysitter & Childcare"),
  real_estate("Real Estate"),
  healthcare("Healthcare & Medical"),
  child_and_elder_care("Child & Elder Care"),
  labor_worker("Labor Worker"),
  pharmaceuticals("Pharmaceuticals"),
  security_services("Security Services"),
  maintenance_and_repair("Maintenance & Repair"),
  community_services("Community & Development Services"),
  textile("Textile Services"),
  maritime("Maritime Services"),
  aviation("Aviation Services"),
  printing_publishing("Printing & Publishing"),
  customer_service("Customer Service & Front Desk"),
  lab_and_technical("Lab & Technical Services"),
  veterinary("Veterinary & Animal Welfare"),
  beauty("Hair & Beauty Services"),
  pet_care("Pet Care Services"),
  delivery("Delivery"),
  supervisor_manager("Supervisor / Manager"),
  teacher_trainer("Teacher, Tutor & Trainer"),
  fitness_coach("Fitness & Personal Trainer"),
  tour_guide("Tour Guide"),
  artist_writer("Artist & Copywriter"),
  elder_disability_care("Elderly & Disability Support"),
  mining("Mining"),
  warehouse("Warehouse, Storage & Distribution"),
  accounting_audit("Accounting & Auditing"),
  admin_support("Admin Accounting & Office Support"),
  engineer_technician("Engineer & Technician"),
  gardening("Gardening & Landscaping"),
  receptionist("Receptionist"),
  procurement("Purchasing & Inventory"),
  creative_media("Creative Arts & Media"),
  banking_finance("Banking & Financial Services"),
  florist("Florist"),
  butcher("Butcher"),
  packer("Picker & Packer"),
  bartender("Bartender"),
  horticulturist("Horticulturist"),
  barista("Barista"),
  estimator("Estimator, Assessor & Surveyor"),
  dentist("Dentist"),
  photographer("Photographer & Videographer"),
  linguist_therapist("Linguist & Therapist"),
  software_analyst("IT Analyst & Software Engineer"),
  interior_designer("Interior Designer"),
  stylist("Stylist"),
  occupational_therapist("Occupational Therapist"),
  hr_recruiter("HR & Recruitment"),
  kitchen_staff("Kitchen & Bakery Staff"),
  mover("Mover"),
  cleaner("Cleaner"),
  cleaning_services("Cleaning & Housekeeping Services"),
  hotel_staff("Hotel Staff & Front Desk"),
  massage_spa("Massage & Spa Staff"),
  restaurant_staff("Restaurant, Bar & Cafe Staff"),
  agriculture_conservation("Agriculture, Animal & Conservation"),
  legal("Legal"),
  business_development("Business Development"),
  hotel_management("Hotel Management & Reception"),
  restaurant_management("Restaurant, Bar & Cafe Management"),
  event_manager("Event Manager"),
  medical_manager("Medical Management"),
  manufacturing_logistics("Manufacturing, Transport & Logistics"),
  management("Management"),
  architecture("Architecture & Design"),
  graphic_design("Graphic Design"),
  cashier("Cashier"),
  commerce_services("Commerce & Services"),
  construction_services("Construction Trade & Services"),
  welder_boiler("Welder & Boilermaker"),
  pastry_chef("Chef & Pastry Cook"),
  cabinet_maker("Cabinet Maker"),
  assembler_mechanic("Assembler, Turner & Mechanic"),
  tailor("Tailor"),
  carpenter("Carpenter"),
  bike_mechanic("Bicycle Mechanic"),
  car_mechanic("Car Mechanic"),
  plumber("Plumber"),
  electrician("Electrician"),
  marketing_media("Marketing & Media"),
  call_center("Call Center & Customer Support"),
  gaming("Gaming"),
  retail_assistant("Retail Assistant"),
  warehouse_assistant("Warehouse Assistant"),
  dental_assistant("Dental Assistant"),
  driver("Driver"),
  psychology_social("Psychology, Counseling & Social Work"),
  consultant("Consultant"),
  machine_operator("Machine & Equipment Operator"),
  construction("Construction"),
  nurse("Nurse"),
  sales_rep("Sales Representative / Consultant"),
  quality_control("Quality Assurance & Control"),
  chef("Chef / Cook");

  final String label;
  const EnumTypeJobCategory(this.label);
}
